animations {
  bezier=linear, 1, 1, 0, 0
  animation=fadeIn, 1, 5, linear
  animation=fadeOut, 1, 5, linear
  animation=inputFieldDots, 1, 2, linear
  enabled=true
}

background {
  color=rgba(0, 0, 0, 1.0)
}

general {
  hide_cursor=true
  ignore_empty_input=true
}

input-field {
  size=10%, 3%
  check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
  fade_on_empty=false
  fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg
  fail_text=$PAMFAIL$FPRINTFAIL
  font_color=rgb(255, 255, 255)
  font_family=Sans
  halign=center
  inner_color=rgba(0, 0, 0, 0.0)
  outer_color=rgba(255,255,255,1)
  outline_thickness=3
  placeholder_text=Input password...
  position=0, 10%
  rounding=30
  valign=bottom
}

label {
  font_family=Sans
  font_size=80
  halign=center
  position=0, 200
  text=$TIME
  valign=center
}

label {
  font_family=Sans
  font_size=25
  halign=center
  position=0, 130
  text=cmd[update:60000] date +"%A, %d %B %Y"
  valign=center
}
