-- Generated by Home Manager.
-- See https://wiki.hypr.land/Configuring/Start/

-- settings.locals
local fileManager = "nautilus"
local mainMod = "SUPER"
local menu = "fuzzel"
local terminal = "kitty"

-- settings.curve
hl.curve("quick", ({ type = "bezier", points = { {0.15, 0}, {0.1, 1} } }))

-- settings.animation
hl.animation({
  ["bezier"] = "quick",
  ["enabled"] = true,
  ["leaf"] = "global",
  ["speed"] = 1
})

-- settings.bind
hl.bind((mainMod .. " + RETURN"), (hl.dsp.exec_cmd(terminal)))
hl.bind((mainMod .. " + Q"), (hl.dsp.window.close()))
hl.bind((mainMod .. " + E"), (hl.dsp.exec_cmd(fileManager)))
hl.bind((mainMod .. " + V"), (hl.dsp.window.float({ action = "toggle" })))
hl.bind((mainMod .. " + R"), (hl.dsp.exec_cmd(menu)))
hl.bind((mainMod .. " + P"), (hl.dsp.window.pin({ action = "toggle" })))
hl.bind((mainMod .. " + L"), (hl.dsp.exec_cmd("hyprlock &")))
hl.bind("CTRL + SHIFT + 4", (hl.dsp.exec_cmd("grim -g \"$(slurp -d)\" - | wl-copy")))
hl.bind((mainMod .. " + F"), (hl.dsp.window.fullscreen({"fullscreen", toggle})))
hl.bind((mainMod .. " + G"), (hl.dsp.group.toggle()))
hl.bind((mainMod .. " + left"), (hl.dsp.focus({ direction = "left" })))
hl.bind((mainMod .. " + right"), (hl.dsp.focus({ direction = "right" })))
hl.bind((mainMod .. " + up"), (hl.dsp.focus({ direction = "up" })))
hl.bind((mainMod .. " + down"), (hl.dsp.focus({ direction = "down" })))
hl.bind((mainMod .. " + CONTROL + left"), (hl.dsp.focus({ workspace = "e-1" })))
hl.bind((mainMod .. " + CONTROL + right"), (hl.dsp.focus({ workspace = "e+1" })))
hl.bind((mainMod .. " + TAB"), (hl.dsp.focus({ workspace = "previous" })))
hl.bind((mainMod .. " + CONTROL + SHIFT + left"), (hl.dsp.window.move({ workspace = "e-1" })))
hl.bind((mainMod .. " + CONTROL + SHIFT + right"), (hl.dsp.window.move({ workspace = "e+1" })))
hl.bind((mainMod .. " + ALT + left"), (hl.dsp.workspace.move({ monitor = "-1" })))
hl.bind((mainMod .. " + ALT + right"), (hl.dsp.workspace.move({ monitor = "+1" })))
hl.bind((mainMod .. " + mouse:272"), (hl.dsp.window.drag()), ({ mouse = true }))
hl.bind((mainMod .. " + mouse:273"), (hl.dsp.window.resize()), ({ mouse = true }))
hl.bind("XF86AudioRaiseVolume", (hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+")), ({ locked = true, repeating = true }))
hl.bind("XF86AudioLowerVolume", (hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-")), ({ locked = true, repeating = true }))
hl.bind("XF86AudioMute", (hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle")), ({ locked = true, repeating = true }))
hl.bind("XF86AudioMicMute", (hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle")), ({ locked = true, repeating = true }))
hl.bind("XF86MonBrightnessUp", (hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+")), ({ locked = true, repeating = true }))
hl.bind("XF86MonBrightnessDown", (hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-")), ({ locked = true, repeating = true }))
hl.bind("XF86AudioNext", (hl.dsp.exec_cmd("playerctl next")), ({ locked = true }))
hl.bind("XF86AudioPause", (hl.dsp.exec_cmd("playerctl play-pause")), ({ locked = true }))
hl.bind("XF86AudioPlay", (hl.dsp.exec_cmd("playerctl play-pause")), ({ locked = true }))
hl.bind("XF86AudioPrev", (hl.dsp.exec_cmd("playerctl previous")), ({ locked = true }))
hl.bind("switch:on:Lid Switch", (hl.dsp.exec_cmd("hyprctl eval 'hl.monitor({ output = \"desc:AU Optronics 0x4F8A\", disabled = true })'")), ({ locked = true }))
hl.bind("switch:off:Lid Switch", (hl.dsp.exec_cmd("hyprctl eval 'hl.monitor({ output = \"desc:AU Optronics 0x4F8A\", disabled = false })'")), ({ locked = true }))

-- settings.config
hl.config({
  ["decoration"] = {
    ["active_opacity"] = 1.0,
    ["blur"] = {
      ["brightness"] = 1.0,
      ["contrast"] = 0.8916,
      ["enabled"] = true,
      ["passes"] = 2,
      ["size"] = 20,
      ["vibrancy"] = 1.0,
      ["vibrancy_darkness"] = 0.5
    },
    ["rounding"] = 5,
    ["rounding_power"] = 2,
    ["shadow"] = {
      ["enabled"] = false
    }
  },
  ["dwindle"] = {
    ["preserve_split"] = true
  },
  ["general"] = {
    ["allow_tearing"] = false,
    ["border_size"] = 2,
    ["col"] = {
      ["active_border"] = "rgba(c061cbee)",
      ["inactive_border"] = "rgba(bfbfbfaa)"
    },
    ["gaps_in"] = 0,
    ["gaps_out"] = 0,
    ["layout"] = "dwindle",
    ["resize_on_border"] = false
  },
  ["group"] = {
    ["col"] = {
      ["border_active"] = "rgba(3584e4ff)",
      ["border_inactive"] = "rgba(99c1f1ff)"
    },
    ["groupbar"] = {
      ["col"] = {
        ["active"] = "rgba(3584e4ff)",
        ["inactive"] = "rgba(99c1f1ff)"
      },
      ["font_size"] = 12,
      ["height"] = 16,
      ["indicator_height"] = 1
    }
  },
  ["input"] = {
    ["follow_mouse"] = 1,
    ["kb_layout"] = "us",
    ["kb_variant"] = "altgr-intl",
    ["numlock_by_default"] = true,
    ["touchpad"] = {
      ["natural_scroll"] = true
    }
  },
  ["master"] = {
    ["new_status"] = "master"
  },
  ["misc"] = {
    ["background_color"] = "0x000000",
    ["disable_hyprland_logo"] = true,
    ["focus_on_activate"] = true,
    ["force_default_wallpaper"] = 0
  }
})

-- settings.device
hl.device({
  ["name"] = "epic-mouse-v1",
  ["sensitivity"] = -0.5
})

-- settings.env
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- settings.gesture
hl.gesture({
  ["action"] = "workspace",
  ["direction"] = "horizontal",
  ["fingers"] = 3
})

-- settings.monitor
hl.monitor({
  ["mode"] = "1920x1080@60",
  ["output"] = "desc:AU Optronics 0x4F8A",
  ["position"] = "0x0",
  ["scale"] = 1
})
hl.monitor({
  ["mode"] = "2560x1440@75",
  ["output"] = "desc:HP Inc. HP E27q G5 CNC42530PR",
  ["position"] = "-2560x0",
  ["scale"] = 1
})
hl.monitor({
  ["mode"] = "2560x1440@120",
  ["output"] = "desc:Dell Inc. DELL U2724DE 7W4FCP3",
  ["position"] = "-2560x0",
  ["scale"] = 1
})

-- settings.on
hl.on("hyprland.start", (function()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("nm-applet")
  hl.exec_cmd("waybar")
end))

-- settings.window_rule
hl.window_rule({
  ["match"] = {
    ["class"] = ".*"
  },
  ["name"] = "Ignore maximise requests from apps",
  ["suppress_event"] = "maximize"
})
hl.window_rule({
  ["center"] = true,
  ["float"] = true,
  ["match"] = {
    ["initial_class"] = "^thunderbird$",
    ["initial_title"] = "^Write"
  },
  ["name"] = "Thunderbird composing"
})
hl.window_rule({
  ["center"] = true,
  ["float"] = true,
  ["match"] = {
    ["initial_class"] = "^org.gnome.NautilusPreviewer$"
  },
  ["name"] = "Nautilus Previewer"
})
hl.window_rule({
  ["group"] = "set",
  ["match"] = {
    ["class"] = "^org.gnome.Papers$"
  },
  ["name"] = "Group Papers windows"
})

-- startup
hl.on("hyprland.start", function()
  hl.exec_cmd("/nix/store/2avx2c74smgw4ghki0qlnc0scgpfycbl-dbus-1.16.2/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target")
end)

-- extraConfig
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end
