## Brew
brew "bat"
brew "btop"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "lazygit"
brew "lf"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "stow"

# Archives
brew "zip"
brew "unzip"

# Misc
brew "cairo"
brew "cocoapods"
brew "pinentry-mac"

# Utils
brew "coreutils"
brew "curl"
brew "make"
brew "trash-cli"
brew "tree-sitter"

## Casks

# Dev
cask "eclipse-ide"
cask "mactex"
cask "visual-studio-code"

# Communications
cask "element"
cask "signal"
cask "thunderbird"

# Utils
cask "drawio"
cask "firefox"
cask "kitty"
cask "logi-options+"
cask "onlyoffice"
cask "orbstack"
cask "qobuz"
cask "vlc"
cask "zotero"

## MAS apps
mas "WhatsApp", id: 310633997
mas "Xcode", id: 497799835
